name: CI

on:
  push:
    branches:
      - physics_kernel

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: physics_kernel

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -yq libhdf5-dev mpich libmpich-dev

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: $HOME/deps
          key: deps-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Build Kokkos
        run: |
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$HOME/deps/kokkos:$HOME/deps/cabana:$HOME/deps/omega_h:$HOME/deps/engpar
          git clone https://github.com/kokkos/kokkos.git
          cd kokkos
          git checkout 580dba5
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/deps/kokkos \
                  -DKokkos_ENABLE_SERIAL=ON \
                  -DKokkos_ENABLE_OPENMP=OFF \
                  -DCMAKE_CXX_COMPILER=$(which mpicxx) \
                  -DCMAKE_C_COMPILER=$(which mpicc) \
                  -DKokkos_ENABLE_CUDA_LAMBDA=off
          make -j$(nproc) && make install
          
      - name: Build EnGPar
        run: |
          git clone https://github.com/SCOREC/EnGPar.git
          cmake -S EnGPar -B engpar-build \
            -DCMAKE_INSTALL_PREFIX=$HOME/deps/engpar \
            -DCMAKE_C_COMPILER=mpicc \
            -DCMAKE_CXX_COMPILER=mpicxx \
            -DCMAKE_CXX_FLAGS="-std=c++11" \
            -DBUILD_SHARED_LIBS=ON \
            -DENABLE_PARMETIS=OFF \
            -DENABLE_PUMI=OFF \
            -DIS_TESTING=OFF
          cmake --build engpar-build --target install -j

      - name: Build Cabana
        run: |
          git clone https://github.com/ECP-copa/Cabana.git
          cd Cabana
          git checkout 86b41a2
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE="Release" \
                  -DCMAKE_INSTALL_PREFIX=$HOME/deps/cabana \
                  -DCMAKE_CXX_COMPILER=$(which mpicxx) \
                  -DKokkos_ROOT=$HOME/deps/kokkos \
                  -DCabana_ENABLE_TESTING=OFF \
                  -DCabana_ENABLE_EXAMPLES=OFF \
                  -DCMAKE_DISABLE_FIND_PACKAGE_HDF5=ON
          make -j$(nproc) && make install

      - name: Build Omega_h
        run: |
          git clone https://github.com/SCOREC/omega_h.git
          cd omega_h
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/deps/omega_h \
                  -DCMAKE_C_COMPILER=$(which mpicc) \
                  -DCMAKE_CXX_COMPILER=$(which mpicxx) \
                  -DMPIEXEC_EXECUTABLE=srun \
                  -DOmega_h_USE_Kokkos=ON \
                  -DKokkos_PREFIX=/home/runner/deps/kokkos/lib/cmake \
                  -DOmega_h_USE_MPI=ON \
          make -j$(nproc) && make install

      - name: Build PUMIPIC
        run: |
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$HOME/deps/kokkos:$HOME/deps/cabana:$HOME/deps/omega_h:$HOME/deps/engpar
          git clone https://github.com/Fuad-HH/pumi-pic.git
          cd pumi-pic
          git checkout make_search_class
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/deps/pumi_pic \
                  -DCMAKE_C_COMPILER=$(which mpicc) \
                  -DCMAKE_CXX_COMPILER=$(which mpicxx) \
                  -DKokkos_ROOT=$HOME/deps/kokkos \
                  -DOmega_h_ROOT=$HOME/deps/omega_h \
                  -DCabana_ROOT=$HOME/deps/cabana \
                  -DENABLE_CABANA=ON \
                  -DCMAKE_CXX_STANDARD=17 \
                  -DEnGPar_PREFIX=$HOME/deps/engpar \
                  -DEnGPar_DIR=$HOME/deps/engpar/lib/cmake/EnGPar
          make -j$(nproc) && make install

      - name: Build PumiUMTally
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=$(which mpicc) -DCMAKE_CXX_COMPILER=$(which mpicxx) -Dpumipic_ROOT=$HOME/deps/pumi_pic -DCabana_ROOT=$HOME/deps/cabana -DPUMI_MEASURE_TIME=ON -DHDF5_ROOT=/usr
          make -j$(nproc)
          ctest --output-on-failure -j$(nproc)

