name: Static Analysis

on:
  push:
  workflow_dispatch:

env:
  DEPS_DIR: ${{ github.workspace }}/deps

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          deps-dir: ${{ env.DEPS_DIR }}
          extra-system-packages: clang-tidy-20 libomp-20-dev

      - name: Configure pumi-tally
        run: |
          # Some dependencies (e.g. Omega_h) needs MPI which is not
          # automatically included in the compiler flags.
          TIDY_CMD="clang-tidy-20"
          for flag in $(mpicxx -show | tr ' ' '\n' | grep '^-I'); do
            TIDY_CMD="${TIDY_CMD};--extra-arg=${flag}"
          done

          cmake -S . -B build \
            -DCMAKE_PREFIX_PATH=$DEPS_DIR \
            -DCMAKE_CXX_COMPILER=mpicxx \
            -DCMAKE_C_COMPILER=mpicc \
            -DBUILD_SHARED_LIBS=ON \
            -DPUMITALLY_ENABLE_DEGAS2=ON \
            -DCMAKE_CXX_CLANG_TIDY=${TIDY_CMD}

      - name: Build with clang-tidy
        run: cmake --build build
